// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var NodeMachineId = require("node-machine-id");

var a = NodeMachineId.machineIdSync();

exports.a = a;
/* a Not a pure module */
